-- DROP SCHEMA IF EXISTS review_tables;
-- CREATE SCHEMA review_tables;

DROP TABLE IF EXISTS reviews CASCADE;
CREATE TABLE reviews (
 --product_id     int GENERATED BY DEFAULT AS IDENTITY,
 review_id      int UNIQUE,
 product_id     int GENERATED BY DEFAULT AS IDENTITY,
 rating         int NOT NULL,
 post_date           date NOT NULL,
 summary        varchar(250) NOT NULL,
 body           varchar(500) NOT NULL,
 recommend      boolean NOT NULL,
 reported       boolean NOT NULL,
 reviewer_name  varchar(50) NOT NULL,
 reviewer_email varchar(50) NOT NULL,
 response       varchar(250),
 helpfulness    integer NOT NULL,
 PRIMARY KEY (review_id)
);
--TODO add unique constraints on email and name...
DROP INDEX if EXISTS product_key;
CREATE INDEX product_key ON reviews (product_id);

copy reviews from '/Users/jverploeg/Desktop/reviews.csv' delimiter ',' csv header;



-- characteristics
DROP TABLE IF EXISTS characteristics CASCADE;
CREATE TABLE characteristics (
 characteristic_id int PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
 char_name              varchar(50) NOT NULL,
 char_value             numeric(5,2)
);






-- ************************************** characteristics-reviews
DROP TABLE IF EXISTS characteristics_reviews CASCADE;
CREATE TABLE characteristics_reviews
(
 id               int PRIMARY KEY GENERATED ALWAYS AS IDENTITY (
 start 1
 ),
 characteristic_id int NOT NULL,
 review_id         int UNIQUE,
 --CONSTRAINT PK_characterisctics PRIMARY KEY ( id ),
 CONSTRAINT fk_review FOREIGN KEY ( review_id ) REFERENCES reviews ( review_id ),
 CONSTRAINT fk_char FOREIGN KEY ( characteristic_id ) REFERENCES characteristics ( characteristic_id )
);


-- ************************************** photos
DROP TABLE IF EXISTS photos;
CREATE TABLE photos
(
 review_id int GENERATED BY DEFAULT AS IDENTITY,
 product_id     int not null,
 id  int generated always as identity,
 url       varchar(150) NOT NULL,
 --CONSTRAINT PK_photos PRIMARY KEY ( review_id ),
 CONSTRAINT fk_reviews FOREIGN KEY ( review_id ) REFERENCES reviews ( review_id )
--  CONSTRAINT fk_products FOREIGN KEY ( product_id ) REFERENCES reviews ( product_id )
);
--copy photos (review_id, url)  from '/Users/jverploeg/Desktop/photos.csv' delimiter ','  csv header;

-- ************************************** ratings
DROP TABLE IF EXISTS ratings CASCADE;
CREATE TABLE ratings
(
 product_id integer PRIMARY KEY NOT NULL,
 one          integer NOT NULL,
 two          integer NOT NULL,
 three          integer NOT NULL,
 four          integer NOT NULL,
 five          integer NOT NULL
);

-- ************************************** products
DROP TABLE IF EXISTS products;
CREATE TABLE products
(
 product_id      int UNIQUE NOT NULL,
 review_count    int NOT NULL,
 ratings_val     numeric(4,3),
 recommend_count integer NOT NULL,
 characteristics integer NOT NULL,
 CONSTRAINT fk_reviews FOREIGN KEY ( product_id )
 REFERENCES ratings ( product_id ),
 CONSTRAINT fk_chars FOREIGN KEY ( characteristics ) REFERENCES characteristics_reviews ( id )
);






